"""Generate cdrdao mastering files for PDv1 draft discs."""

from __future__ import annotations

from dataclasses import asdict, dataclass
import json
from pathlib import Path

from .beacon import BEACON_SECONDS, write_beacon_wav
from .identity import DRAFT_VERSION, FORMAT_NAME, PDIdentity

BEACON_PROFILE = "dtmf-draft-a"


def _q(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def _ascii_cdtext(value: str, *, limit: int = 48) -> str:
    # Draft 0.2 intentionally uses conservative ASCII CD-TEXT for old head units.
    cleaned = "".join(ch if 32 <= ord(ch) <= 126 else "?" for ch in value)
    return cleaned[:limit]


def _msf(seconds: int) -> str:
    minutes, sec = divmod(seconds, 60)
    return f"{minutes:02d}:{sec:02d}:00"


def _cdtext_block(identity: PDIdentity, short: str, performer: str) -> list[str]:
    return [
        "CD_TEXT {",
        "  LANGUAGE_MAP { 0 : EN }",
        "  LANGUAGE 0 {",
        f"    TITLE {_q(short)}",
        f"    PERFORMER {_q(performer)}",
        f"    MESSAGE {_q(identity.machine_id)}",
        "  }",
        "}",
        "",
    ]


def _track_cdtext_block(short: str, performer: str) -> list[str]:
    return [
        "CD_TEXT {",
        "  LANGUAGE 0 {",
        f"    TITLE {_q(short)}",
        f"    PERFORMER {_q(performer)}",
        "  }",
        "}",
    ]


def render_toc(
    identity: PDIdentity,
    *,
    title: str,
    short_title: str | None = None,
    cd_text: bool = True,
) -> str:
    """Render the physical TOC.

    CD-TEXT is a redundant/optional PDv1 channel and does not alter the canonical
    eight-track timing identity. The no-CD-TEXT variant exists so compatibility
    testing can isolate metadata behavior without changing the PD identity.
    """
    short = _ascii_cdtext(short_title or title, limit=32)
    performer = "PLAYLIST DISC"
    lines = [
        f"// Generated by playlist-disc; {FORMAT_NAME} Draft {DRAFT_VERSION}",
        "CD_DA",
        "",
    ]
    if cd_text:
        lines.extend(_cdtext_block(identity, short, performer))

    for index, duration in enumerate(identity.track_durations, start=1):
        lines.append("TRACK AUDIO")
        if cd_text:
            lines.extend(_track_cdtext_block(short, performer))
        if index == 1:
            lines.append('AUDIOFILE "beacon.wav" 0')
            remaining = duration - int(BEACON_SECONDS)
            if remaining < 0:
                raise AssertionError("beacon cannot fit track 1")
            if remaining:
                lines.append(f"SILENCE {_msf(remaining)}")
        else:
            lines.append(f"SILENCE {_msf(duration)}")
        lines.append("")
    return "\n".join(lines)


@dataclass(frozen=True, slots=True)
class BuildManifest:
    format: str
    draft: str
    id: str
    machine_id: str
    namespace: str
    check_digit: int
    title: str
    short_title: str
    track_durations_seconds: tuple[int, ...]
    total_seconds: int
    toc_sha256: str
    beacon_profile: str
    cd_text: bool


def build_bundle(
    identity: PDIdentity,
    output_dir: str | Path,
    *,
    title: str,
    short_title: str | None = None,
    cd_text: bool = True,
) -> Path:
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    short = short_title or title
    write_beacon_wav(identity, output / "beacon.wav")
    (output / "disc.toc").write_text(
        render_toc(
            identity,
            title=title,
            short_title=short,
            cd_text=cd_text,
        ),
        encoding="utf-8",
    )
    manifest = BuildManifest(
        format=FORMAT_NAME,
        draft=DRAFT_VERSION,
        id=identity.canonical,
        machine_id=identity.machine_id,
        namespace=identity.namespace,
        check_digit=identity.check_digit,
        title=title,
        short_title=short,
        track_durations_seconds=identity.track_durations,
        total_seconds=identity.total_seconds,
        toc_sha256=identity.toc_signature,
        beacon_profile=BEACON_PROFILE,
        cd_text=cd_text,
    )
    (output / "manifest.json").write_text(
        json.dumps(asdict(manifest), indent=2) + "\n", encoding="utf-8"
    )
    return output
